name: example
author: Herohtar <belac1186@gmail.com>

environment:
  sdk: ">=2.0.0-dev.58.0 <2.0.0"

dependencies:
  wordnik: ^0.4.0

  # Used for the example, but not required for the API
  credentials_helper: ^1.0.1
