name: wordnik
description: An API client library for working with the Wordnik API in Dart.
version: 1.0.0
author: "Herohtar <belac1186@gmail.com>"
homepage: https://github.com/herohtar/wordnik-dart

dependencies:
  http: ^0.12.0+2
  intl: ^0.15.7
  json_annotation: ^1.0.0

dev_dependencies:
  test: ^1.3.0
  build_runner: ^0.9.2
  json_serializable: ^1.0.0
  credentials_helper: ^1.0.3

environment:
  sdk: ">=2.0.0-dev <3.0.0"
