name: wordnik
description: Wordnik API for Dart.
version: 0.1.0
author: "Herohtar <belac1186@gmail.com>"
homepage: https://github.com/herohtar/wordnik-dart

dependencies:
  http: ^0.11.3+16
  intl: ^0.15.6
  json_annotation: ^0.2.5

dev_dependencies:
  test: ^1.2.0
  build_runner: ^0.8.9
  json_serializable: ^0.5.4

environment:
  sdk: ">=2.0.0-dev.58.0 <2.0.0"
